[[CUDA_SDK_static]]
arch = "x86_64"
git-tree-sha1 = "5421717d165fd947b2cbaaff188a9fc4b996a6e7"
libc = "glibc"
os = "linux"

    [[CUDA_SDK_static.download]]
    sha256 = "320815b47422a8ebe0b1cc89fe1b562fd831500dc0d898b4aefe64f44c6d102d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_SDK_static_jll.jl/releases/download/CUDA_SDK_static-v13.2.1+0/CUDA_SDK_static.v13.2.1.x86_64-linux-gnu.tar.xz"
[[CUDA_SDK_static]]
arch = "aarch64"
git-tree-sha1 = "247b800a099a68b5089b5ea92946a9502703ad8b"
libc = "glibc"
os = "linux"

    [[CUDA_SDK_static.download]]
    sha256 = "c4a0ba9b6aa230b7e0b0017431ae30784d7744d1a0b93e800102c144d1772eb7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_SDK_static_jll.jl/releases/download/CUDA_SDK_static-v13.2.1+0/CUDA_SDK_static.v13.2.1.aarch64-linux-gnu.tar.xz"
[[CUDA_SDK_static]]
arch = "x86_64"
git-tree-sha1 = "a0696905429b0019b14ef98b4c33eb8dd5b5ccef"
os = "windows"

    [[CUDA_SDK_static.download]]
    sha256 = "2ff8dce02a25691b6b4e03978a3ec0c3d4dcb754277e9c218e73e30018fe9835"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_SDK_static_jll.jl/releases/download/CUDA_SDK_static-v13.2.1+0/CUDA_SDK_static.v13.2.1.x86_64-w64-mingw32.tar.xz"
