# Autogenerated wrapper script for CUDA_SDK_static_jll for x86_64-linux-gnu-cuda+13
JLLWrappers.@generate_wrapper_header("CUDA_SDK_static")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
